# Generated by Django 3.1.4 on 2020-12-15 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="price",
            field=models.DecimalField(
                decimal_places=2, default=100, max_digits=9, verbose_name="price"
            ),
            preserve_default=False,
        ),
    ]
