export const MOVIE_PEEK_LIST_REQUEST = 'MOVIE_PEEK_LIST_REQUEST';
export const MOVIE_PEEK_LIST_RESPONSE = 'MOVIE_PEEK_LIST_RESPONSE';
export const MOVIE_DETAIL_REQUEST = 'MOVIE_DETAIL_REQUEST';
export const MOVIE_DETAIL_RESPONSE = 'MOVIE_DETAIL_RESPONSE';
export const MOVIE_RECOMMENDTION_LIST = 'MOVIE_RECOMMENDTION_LIST';
export const MOVIE_FAN_FAVORITE_LIST = 'MOVIE_FAN_FAVORITE_LIST';

export const CELEBRITY_BORN_TODAY_LIST = 'CELEBRITY_BORN_TODAY_LIST';

export const AUTH_SIGNIN_REQUEST = 'AUTH_SIGNIN_REQUEST';
export const AUTH_SIGNIN_RESPONSE = 'AUTH_SIGNIN_RESPONSE';
export const AUTH_SIGNUP_REQUEST = 'AUTH_SIGNUP_REQUEST';
export const AUTH_SIGNUP_RESPONSE = 'AUTH_SIGNUP_RESPONSE';
export const AUTH_SIGNOUT = 'AUTH_SIGNOUT';