export const MOVIE_PEEK_LIST = 'MOVIE_PEEK_LIST';
export const MOVIE_RECOMMENDTION_LIST = 'MOVIE_RECOMMENDTION_LIST';
export const MOVIE_FAN_FAVORITE_LIST = 'MOVIE_FAN_FAVORITE_LIST';

export const CELEBRITY_BORN_TODAY_LIST = 'CELEBRITY_BORN_TODAY_LIST';