# Generated by Django 3.1.4 on 2020-12-13 04:19

import celebrities.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Celebrity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('date_of_birth', models.DateField(verbose_name='Date of Birth')),
                ('debut_date', models.DateField(verbose_name='Debut Date')),
                ('description', models.TextField(verbose_name='Description')),
                ('popularity_score', models.DecimalField(decimal_places=2, max_digits=2, verbose_name='Popularity Score')),
                ('image', models.ImageField(upload_to=celebrities.models._get_celebrity_image_url, verbose_name='Celebrity Image')),
            ],
            options={
                'ordering': ('-popularity_score',),
            },
        ),
    ]
