# Generated by Django 3.1.4 on 2020-12-16 14:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=200, unique=True, verbose_name='Checkout Session ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Price')),
                ('completed', models.BooleanField(default=False, verbose_name='Completed')),
                ('completed_time', models.DateTimeField(null=True, verbose_name='Date Time when order was completed')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='Date Time when order was created.')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='movies.movie', verbose_name='Movie')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
