# Generated by Django 3.1.4 on 2020-12-15 13:54

import datetime

import django.utils.timezone
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_auto_20201215_1322"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="completed_time",
            field=models.DateTimeField(
                default=datetime.datetime(2020, 12, 15, 13, 54, 42, 904330, tzinfo=utc),
                verbose_name="Date Time when order was completed",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="created_time",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Date Time when order was created.",
            ),
            preserve_default=False,
        ),
    ]
